/*** annotatorPro plugin ***/
$("#the-img-tag").annotatorPro({
	maxZoom : 2,
	frameWidth : "100%",
	frameHeight : "100%",
	navigator : false,
	navigatorImagePreview : false,
	rubberband : true,
	annotations : [
		{
			id : "tower0801",
			title : "기아",
			text : "K5",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "25%",
			spot_top : "22%",
			spot_width : "6%",
			spot_height : "3.3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"2..38\"]",
		},
		{
			id : "tower0802",
			title : "현대",
			text : "아반떼 AD",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "35.1%",
			spot_top : "21.7%",
			spot_width : "3.9%",
			spot_height : "3.3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"5..112..1571\"]",
		},
		{
			id : "tower0701",
			title : "벤츠",
			text : "전체차량",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "25.1%",
			spot_top : "28.7%",
			spot_width : "4.9%",
			spot_height : "3.3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"68\"]",
		},
		{
			id : "tower0702",
			title : "기아",
			text : "레이",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "30.1%",
			spot_top : "27.9%",
			spot_width : "3.9%",
			spot_height : "3.3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"2..42\"]",
		},
		{
			id : "tower0703",
			title : "기아",
			text : "올 뉴 모닝",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "35.5%",
			spot_top : "29%",
			spot_width : "3.6%",
			spot_height : "3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"2..46..2574\"]",
		},
		{
			id : "tower0704",
			title : "현대",
			text : "아반떼 AD",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "39.1%",
			spot_top : "30.2%",
			spot_width : "4.6%",
			spot_height : "3.2%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"5..112..1571\"]",
		},
		{
			id : "tower0601",
			title : "아우디",
			text : "전체차량",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "25.1%",
			spot_top : "37.2%",
			spot_width : "6%",
			spot_height : "3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"70\"]",
		},
		{
			id : "tower0602",
			title : "현대",
			text : "그랜저IG",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "35.1%",
			spot_top : "37%",
			spot_width : "4%",
			spot_height : "2.5%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"5..96..2569\"]",
		},
		{
			id : "towerHyudai",
			title : "현대",
			text : "전체차량",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "33.4%",
			spot_top : "39.8%",
			spot_width : "2.6%",
			spot_height : "3.7%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"5\"]",
		},
		{
			id : "tower0501",
			title : "현대",
			text : "싼타페DM 더 프라임",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "25.1%",
			spot_top : "44.2%",
			spot_width : "4.9%",
			spot_height : "3.3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"5..110..281\"]",
		},
		{
			id : "tower0502",
			title : "기아",
			text : "더 뉴 쏘렌토",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "30.1%",
			spot_top : "44%",
			spot_width : "4.2%",
			spot_height : "3.4%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"2..56..2611\"]",
		},
		{
			id : "tower0503",
			title : "기아",
			text : "더 뉴 카니발",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "37.5%",
			spot_top : "44.5%",
			spot_width : "6.4%",
			spot_height : "3.3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"2..64..2656\"]",
		},
		{
			id : "tower0401",
			title : "쌍용",
			text : "티볼리",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "30.1%",
			spot_top : "52%",
			spot_width : "4%",
			spot_height : "3.3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"4..91\"]",
		},
		{
			id : "tower0402",
			title : "기아",
			text : "레이",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "35.5%",
			spot_top : "51.7%",
			spot_width : "3.5%",
			spot_height : "3.7%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"2..42\"]",
		},
		{
			id : "tower0403",
			title : "기아",
			text : "올 뉴 모닝",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "39.1%",
			spot_top : "52.2%",
			spot_width : "4.6%",
			spot_height : "3.3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"2..46..2574\"]",
		},
		{
			id : "towerKia",
			title : "기아",
			text : "전체차량",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "33.3%",
			spot_top : "55.7%",
			spot_width : "2.6%",
			spot_height : "4%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"2\"]",
		},
		{
			id : "tower0301",
			title : "아우디",
			text : "전체차량",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "25.1%",
			spot_top : "59.9%",
			spot_width : "4.9%",
			spot_height : "3.3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"70\"]",
		},
		{
			id : "tower0302",
			title : "현대",
			text : "아반떼 AD",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "30.1%",
			spot_top : "60%",
			spot_width : "4.2%",
			spot_height : "3.3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"5..112..1571\"]",
		},
		{
			id : "tower0303",
			title : "기아",
			text : "K3",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "35.1%",
			spot_top : "59.9%",
			spot_width : "3.9%",
			spot_height : "3.3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"2..37\"]",
		},
		{
			id : "tower0304",
			title : "기아",
			text : "스포티지",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "39.1%",
			spot_top : "59.3%",
			spot_width : "4.7%",
			spot_height : "3.7%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"2..54\"]",
		},
		{
			id : "tower0201",
			title : "벤츠",
			text : "전체차량",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "25.1%",
			spot_top : "67.6%",
			spot_width : "4.9%",
			spot_height : "3.3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"68\"]",
		},
		{
			id : "tower0202",
			title : "현대",
			text : "LF쏘나타 뉴라이즈",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "30.1%",
			spot_top : "67.5%",
			spot_width : "4.2%",
			spot_height : "3.5%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"5..111..2588\"]",
		},
		{
			id : "tower0203",
			title : "현대",
			text : "그랜저IG",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "35.1%",
			spot_top : "67.3%",
			spot_width : "3.9%",
			spot_height : "3.8%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"5..96..2569\"]",
		},
		{
			id : "tower0204",
			title : "제네시스",
			text : "G80",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "39.1%",
			spot_top : "67.2%",
			spot_width : "4.8%",
			spot_height : "3.3%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"146..1171\"]",
		},
		{
			id : "tower0101",
			title : "기아",
			text : "스포티지",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "25.1%",
			spot_top : "74%",
			spot_width : "5%",
			spot_height : "4.5%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"2..54\"]",
		},
		{
			id : "tower0102",
			title : "기아",
			text : "더 뉴 카니발",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "30.1%",
			spot_top : "73.7%",
			spot_width : "4.4%",
			spot_height : "5%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"2..64..2656\"]",
		},
		{
			id : "tower0103",
			title : "현대",
			text : "싼타페DM 더 프라임",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "35.1%",
			spot_top : "73.9%",
			spot_width : "3.9%",
			spot_height : "4.7%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"5..110..281\"]",
		},
		{
			id : "tower0104",
			title : "기아",
			text : "더 뉴 쏘렌토",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "39.1%",
			spot_top : "73.7%",
			spot_width : "4.8%",
			spot_height : "4%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"2..56..2611\"]",
		},
		{
			id : "arcadeGenesis",
			title : "제네시스",
			text : "전체차량",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "51%",
			spot_top : "56.7%",
			spot_width : "9.8%",
			spot_height : "5.8%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"146\"]",
		},
		{
			id : "arcadeBMW",
			title : "BMW",
			text : "전체차량",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "62.1%",
			spot_top : "56.5%",
			spot_width : "9.8%",
			spot_height : "5.6%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"67\"]",
		},
		{
			id : "arcadeSpecial",
			title : "테마기획전",
			text : "전체차량",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "52.1%",
			spot_top : "62.9%",
			spot_width : "8.8%",
			spot_height : "7%",
            location : "/cr/theme/list",
		},
		{
			id : "arcadeAudi",
			title : "아우디",
			text : "전체차량",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "62.1%",
			spot_top : "62.7%",
			spot_width : "9.8%",
			spot_height : "6%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"70\"]",
		},
		{
			id : "arcadeSedan",
			title : "대형 승용",
			text : "전체차량",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "51.1%",
			spot_top : "72.3%",
			spot_width : "4.4%",
			spot_height : "4%",
			location:"/cr/search/list?listview=true#page:1._.rows:15._.cho:1._.carType:[\"002005\"]"
		},
		{
			id : "arcadeSUV",
			title : "SUV",
			text : "전체차량",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "56.1%",
			spot_top : "71.7%",
			spot_width : "4.5%",
			spot_height : "4.4%",
			location: "/cr/search/list?listview=true#page:1._.rows:15._.cho:1._.carType:[\"002008\"]"
		},
		{
			id : "arcadeBenz",
			title : "벤츠",
			text : "전체차량",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "62.5%",
			spot_top : "70.8%",
			spot_width : "11%",
			spot_height : "4.8%",
			location : "/cr/search/list?listview=true#page:1._.rows:15._.cg:[\"68\"]",
		},
		{
			id : "arcadeSellcar",
			title : "내차팔기",
			text : "",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "56.5%",
			spot_top : "76.9%",
			spot_width : "7.8%",
			spot_height : "6%",
			location : "/sell/sise"
		},
		{
			id : "arcadeElectric",
			title : "전기차",
			text : "전체차량",
			tint_color : "#fff",
			popup_width : "122",
			popup_height : "60",
			spot_left : "65%",
			spot_top : "75.7%",
			spot_width : "10.8%",
			spot_height : "6%",
            location : "/cr/search/list?listview=true#page:1._.rows:15._.fuel:[\"05\",\"06\",\"07\",\"08\",\"09\"]",
		},
	]
});

/*** custom event ***/
$(function(){
	$(".gnb .bt-flip").on("click", function(){
		var depth1 = $(this).parents(".depth1");

		depth1.toggleClass("active");
	})


	//info layer control
	$("#btMarketInfo").on("click", function(){
		$('#layerMarketInfo').toggle();
		$(this).toggleClass('on');
		$('#layerNaviInfo').hide();
		$("#btNaviInfo").removeClass("on");
	})

	//car click event
	$(document).on('click', '.ndd-popup-box',function(e) {
		// console.log(e.currentTarget);
		// alert("리스트 페이지로 이동합니다.");
		let target = $(e.currentTarget);
		if(target.attr("data-location")){
			location.href = target.attr("data-location");
		}else{
			nayuda.alert("준비 중 입니다.");
		}

	});

	//market info swiper
	var marketSwiper = new Swiper('.market-slider', {
		slidesPerView: 1,
		loop: false,
		speed: 300,
		allowTouchMove : true,
		disableOnInteraction: true,
		observer: true, 
		observeParents: true,
		//autoplay: {
			//delay: 3000,
			//disableOnInteraction: false,
		//},
		pagination: {
			el: '.swiper-pagination',
			type: 'bullets',
			clickable : true,
		}
	});

	$("#todayHidden").on("click", function(){
		$('#layerMarketInfo').toggle();
		$("body").removeClass("modalOpen");
		//cookie make
		nayuda.setCookie("mainNaviTodayHidden","true",1);
	})

	//cookie check on load
	$(document).ready(function(){
		if(nayuda.getCookie("mainNaviTodayHidden") != "true"){
			$("body").addClass("modalOpen");
			$("#layerMarketInfo").css("display", "block");
		}
	})
})